/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-06-23 22:30:22
*/

`include "/home/keyur/my_full_pdk/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v"
`include "JTAG/router_top_jtag_netlist.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    reg[0:0] \resetn ;
    wire[7:0] \data_out_2 ;
    reg[0:0] \read_enb_0 ;
    reg[0:0] \pkt_valid ;
    reg[7:0] \data_in ;
    wire[0:0] \tdo_paden_o ;
    wire[0:0] \vld_out_1 ;
    wire[7:0] \data_out_1 ;
    wire[0:0] \vld_out_0 ;
    reg[0:0] \read_enb_1 ;
    reg[0:0] \read_enb_2 ;
    reg[0:0] \clock ;
    wire[7:0] \data_out_0 ;
    wire[0:0] \err ;
    reg[0:0] \tms ;
    reg[0:0] \tck ;
    reg[0:0] \tdi ;
    wire[0:0] \tdo ;
    reg[0:0] \trst ;
    wire[0:0] \busy ;
    wire[0:0] \vld_out_2 ;


    always #(`CLOCK_PERIOD / 2) clock = ~clock;
    always #(`CLOCK_PERIOD / 2) tck = ~tck;

    router_top uut(
        .\resetn ( \resetn ) , .\data_out_2 ( \data_out_2 ) , .\read_enb_0 ( \read_enb_0 ) , .\pkt_valid ( \pkt_valid ) , .\data_in ( \data_in ) , .\tdo_paden_o ( \tdo_paden_o ) , .\vld_out_1 ( \vld_out_1 ) , .\data_out_1 ( \data_out_1 ) , .\vld_out_0 ( \vld_out_0 ) , .\read_enb_1 ( \read_enb_1 ) , .\read_enb_2 ( \read_enb_2 ) , .\clock ( \clock ) , .\data_out_0 ( \data_out_0 ) , .\err ( \err ) , .\tms ( \tms ) , .\tck ( \tck ) , .\tdi ( \tdi ) , .\tdo ( \tdo ) , .\trst ( \trst ) , .\busy ( \busy ) , .\vld_out_2 ( \vld_out_2 ) 
    );    

    integer i;

    wire[626:0] __serializable__ =
        627'b011011010100000100000001110000101010111111110101000111001011001101100011111110111111100001011011100001011000010110111111101011001001101110100110011111101010111000011111001100111111011001100111100011101011101101110111110000100110101101011010000111100001110110101111101010001100110000100000111100000100010100111011100000110001111101110111100100011001110110111100111010111001010100111100100001101010000000101001110001111000001100000101111101101010111001000111001010010101001011100101110100011100110011101001100010001111000101111111010010011101011000011010000011010000001111110010110000000111100000101110000110101000010101110000001;
    reg[626:0] __serial__;

    wire[7:0] __tmsPattern__ = 8'b 01100110;
    wire[3:0] __preload_chain__ = 4'b0011;

    wire __tdo_pad_out__ = tdo_paden_o ? 1'bz : tdo;

    initial begin
        `ifdef VCD
            $dumpfile("dut.vcd");
            $dumpvars(0, testbench);
        `endif
        \clock = 0 ;
        \resetn = 0 ;
        \pkt_valid = 0 ;
        \read_enb_0 = 0 ;
        \read_enb_1 = 0 ;
        \read_enb_2 = 0 ;
        \data_in = 0 ;
        \tms = 0 ;
        \tck = 0 ;
        \tdi = 0 ;
        \trst = 0 ;

        tms = 1;
        #(`CLOCK_PERIOD) ;
        resetn = ~resetn;
        trst = 1;        
        #(`CLOCK_PERIOD) ;

        /*
            Test PreloadChain Instruction
        */
        shiftIR(__preload_chain__);
        enterShiftDR();

        for (i = 0; i < 627; i = i + 1) begin
            tdi = __serializable__[i];
            #(`CLOCK_PERIOD) ;
        end
        for(i = 0; i< 627; i = i + 1) begin
            __serial__[i] = __tdo_pad_out__;
            #(`CLOCK_PERIOD) ;
        end 

        if(__serial__ !== __serializable__) begin
            $error("EXECUTING_PRELOAD_CHAIN_INST_FAILED");
            $finish;
        end
        exitDR();

        $display("SUCCESS_STRING");
        $finish;
    end

    task shiftIR;
        input[3:0] __instruction__;
        integer i;
        begin
            for (i = 0; i< 5; i = i + 1) begin
                tms = __tmsPattern__[i];
                #(`CLOCK_PERIOD) ;
            end

            // At shift-IR: shift new instruction on tdi line
            for (i = 0; i < 4; i = i + 1) begin
                tdi = __instruction__[i];
                if(i == 3) begin
                    tms = __tmsPattern__[5];     // exit-ir
                end
                #(`CLOCK_PERIOD) ;
            end

            tms = __tmsPattern__[6];     // update-ir 
            #(`CLOCK_PERIOD) ;
            tms = __tmsPattern__[7];     // run test-idle
            #(`CLOCK_PERIOD * 3) ;
        end
    endtask

    task enterShiftDR;
        begin
            tms = 1;     // select DR
            #(`CLOCK_PERIOD) ;
            tms = 0;     // capture DR -- shift DR
            #(`CLOCK_PERIOD * 2) ;
        end
    endtask

    task exitDR;
        begin
            tms = 1;     // Exit DR -- update DR
            #(`CLOCK_PERIOD * 2) ;
            tms = 0;     // Run test-idle
            #(`CLOCK_PERIOD) ;
        end
    endtask
endmodule
