
/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-06-23 22:30:24
*/
`include "/home/keyur/my_full_pdk/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v"
`include "JTAG/router_top_jtag_netlist.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    reg[0:0] \resetn ;
    wire[7:0] \data_out_2 ;
    reg[0:0] \read_enb_0 ;
    reg[0:0] \pkt_valid ;
    reg[7:0] \data_in ;
    wire[0:0] \tdo_paden_o ;
    wire[0:0] \vld_out_1 ;
    wire[7:0] \data_out_1 ;
    wire[0:0] \vld_out_0 ;
    reg[0:0] \read_enb_1 ;
    reg[0:0] \read_enb_2 ;
    reg[0:0] \clock ;
    wire[7:0] \data_out_0 ;
    wire[0:0] \err ;
    reg[0:0] \tms ;
    reg[0:0] \tck ;
    reg[0:0] \tdi ;
    wire[0:0] \tdo ;
    reg[0:0] \trst ;
    wire[0:0] \busy ;
    wire[0:0] \vld_out_2 ;


    always #(`CLOCK_PERIOD / 2) clock = ~clock;
    always #(`CLOCK_PERIOD / 2) tck = ~tck;

    router_top uut(
        .\resetn ( \resetn ) , .\data_out_2 ( \data_out_2 ) , .\read_enb_0 ( \read_enb_0 ) , .\pkt_valid ( \pkt_valid ) , .\data_in ( \data_in ) , .\tdo_paden_o ( \tdo_paden_o ) , .\vld_out_1 ( \vld_out_1 ) , .\data_out_1 ( \data_out_1 ) , .\vld_out_0 ( \vld_out_0 ) , .\read_enb_1 ( \read_enb_1 ) , .\read_enb_2 ( \read_enb_2 ) , .\clock ( \clock ) , .\data_out_0 ( \data_out_0 ) , .\err ( \err ) , .\tms ( \tms ) , .\tck ( \tck ) , .\tdi ( \tdi ) , .\tdo ( \tdo ) , .\trst ( \trst ) , .\busy ( \busy ) , .\vld_out_2 ( \vld_out_2 ) 
    );

    integer i, __all_errors__, __error__;

    reg [614:0] __scanInSerial__;
    reg [597:0] __vectors__ [0:9];
    reg [614:0] __gmOutput__ [0:9];

    wire[7:0] __tmsPattern__ = 8'b 01100110;
    wire[3:0] __preloadChain__ = 4'b 0011;

    wire __tdo_pad_out__ = tdo_paden_o ? 1'bz : tdo;

    initial begin
        `ifdef VCD
            $dumpfile("dut.vcd"); // DEBUG
            $dumpvars(0, testbench);
        `endif
        __all_errors__ = 0;
        \clock = 1 ;
        \resetn = 1 ;
        \clock = 0 ;
        \resetn = 0 ;
        \pkt_valid = 0 ;
        \read_enb_0 = 0 ;
        \read_enb_1 = 0 ;
        \read_enb_2 = 0 ;
        \data_in = 0 ;
        \tms = 1 ;
        \tck = 0 ;
        \tdi = 0 ;
        \trst = 0 ;

        $readmemb("ASM/test_vector.bin", __vectors__);
        $readmemb("ASM/expected_output.bin", __gmOutput__);
        #(`CLOCK_PERIOD) ;
        resetn = ~resetn;
        trst = 1;        
        #(`CLOCK_PERIOD) ;
        test(0, __vectors__[0], __gmOutput__[0]) ;
        test(1, __vectors__[1], __gmOutput__[1]) ;
        test(2, __vectors__[2], __gmOutput__[2]) ;
        test(3, __vectors__[3], __gmOutput__[3]) ;
        test(4, __vectors__[4], __gmOutput__[4]) ;
        test(5, __vectors__[5], __gmOutput__[5]) ;
        test(6, __vectors__[6], __gmOutput__[6]) ;
        test(7, __vectors__[7], __gmOutput__[7]) ;
        test(8, __vectors__[8], __gmOutput__[8]) ;
        test(9, __vectors__[9], __gmOutput__[9]) ;

        if (__all_errors__ > 0) begin
            $error("SIMULATING_TV_FAILED");
            $finish;
        end else begin
            $display("SUCCESS_STRING");
            $finish;
        end
    end

    task test;
        input [31:0] __ordinal__; // integer
        input [597:0] __vector__;
        input [614:0] __goldenOutput__;
        begin
            $display("Testing vector %0d...", __ordinal__);
            // Preload Scan-Chain with TV

            shiftIR(__preloadChain__);
            enterShiftDR();

            for (i = 0; i < 598; i = i + 1) begin
                tdi = __vector__[i];
                if (i == 595) begin
                    tms = 1; // Exit-DR
                end
                if (i == 596) begin
                    tms = 0; // Pause-DR
                end
                if (i == 597) begin
                    tms = 1; // Exit2-DR
                end
                #(`CLOCK_PERIOD) ;
            end

            tms = 0; // Shift-DR
            #(`CLOCK_PERIOD) ;
            // Shift-out response
            __error__ = 0;
            for (i = 0; i< 615;i = i + 1) begin
                tdi = 0;
                __scanInSerial__[i] = __tdo_pad_out__;
                if (__scanInSerial__[i] !=? __goldenOutput__[i]) begin
                    $display("@%0d:\t\tExpected %0b, Got %0b", i, __goldenOutput__[i], __scanInSerial__[i]);
                    __error__ = __error__ + 1;
                end
                if(i == 614) begin
                    tms = 1; // Exit-DR
                end
                #(`CLOCK_PERIOD) ;
            end
            __all_errors__ += __error__;
            tms = 1; // update-DR
            #(`CLOCK_PERIOD) ;
            tms = 0; // run-test-idle
            #(`CLOCK_PERIOD) ;

            if(__scanInSerial__ !=? __goldenOutput__) begin
                $display("Test vector simulation failed: %0d bits mismatched", __error__);
                $display("Expected:\t%0b", __goldenOutput__);
                $display("Got:\t\t%0b", __scanInSerial__);
            end else begin
                $display("Passed vector %0d.", __ordinal__);
            end
        end
    endtask

       task shiftIR;
        input[3:0] __instruction__;
        integer i;
        begin
            for (i = 0; i< 5; i = i + 1) begin
                tms = __tmsPattern__[i];
                #(`CLOCK_PERIOD) ;
            end

            // At shift-IR: shift new instruction on tdi line
            for (i = 0; i < 4; i = i + 1) begin
                tdi = __instruction__[i];
                if(i == 3) begin
                    tms = __tmsPattern__[5];     // exit-ir
                end
                #(`CLOCK_PERIOD) ;
            end

            tms = __tmsPattern__[6];     // update-ir 
            #(`CLOCK_PERIOD) ;
            tms = __tmsPattern__[7];     // run test-idle
            #(`CLOCK_PERIOD * 3) ;
        end
    endtask

    task enterShiftDR;
        begin
            tms = 1;     // select DR
            #(`CLOCK_PERIOD) ;
            tms = 0;     // capture DR -- shift DR
            #(`CLOCK_PERIOD * 2) ;
        end
    endtask

    task exitDR;
        begin
            tms = 1;     // Exit DR -- update DR
            #(`CLOCK_PERIOD * 2) ;
            tms = 0;     // Run test-idle
            #(`CLOCK_PERIOD) ;
        end
    endtask
endmodule
