/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-07-01 09:44:05
*/

`include "../Tech_Lib/sky130_fd_sc_hd.v"
`include "JTAG/router_top_jtag_netlist.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    reg[0:0] \tms ;
    wire[0:0] \err ;
    wire[7:0] \data_out_0 ;
    wire[0:0] \vld_out_2 ;
    wire[7:0] \data_out_1 ;
    reg[0:0] \read_enb_0 ;
    reg[0:0] \tck ;
    reg[0:0] \tdi ;
    reg[0:0] \pkt_valid ;
    wire[7:0] \data_out_2 ;
    reg[0:0] \read_enb_2 ;
    wire[0:0] \tdo_paden_o ;
    reg[0:0] \clock ;
    wire[0:0] \busy ;
    reg[0:0] \read_enb_1 ;
    wire[0:0] \tdo ;
    reg[0:0] \trst ;
    reg[7:0] \data_in ;
    wire[0:0] \vld_out_1 ;
    reg[0:0] \resetn ;
    wire[0:0] \vld_out_0 ;


    always #(`CLOCK_PERIOD / 2) clock = ~clock;
    always #(`CLOCK_PERIOD / 2) tck = ~tck;

    router_top uut(
        .\tms ( \tms ) , .\err ( \err ) , .\data_out_0 ( \data_out_0 ) , .\vld_out_2 ( \vld_out_2 ) , .\data_out_1 ( \data_out_1 ) , .\read_enb_0 ( \read_enb_0 ) , .\tck ( \tck ) , .\tdi ( \tdi ) , .\pkt_valid ( \pkt_valid ) , .\data_out_2 ( \data_out_2 ) , .\read_enb_2 ( \read_enb_2 ) , .\tdo_paden_o ( \tdo_paden_o ) , .\clock ( \clock ) , .\busy ( \busy ) , .\read_enb_1 ( \read_enb_1 ) , .\tdo ( \tdo ) , .\trst ( \trst ) , .\data_in ( \data_in ) , .\vld_out_1 ( \vld_out_1 ) , .\resetn ( \resetn ) , .\vld_out_0 ( \vld_out_0 ) 
    );    

    integer i;

    wire[626:0] __serializable__ =
        627'b000011010100101101100110010001010100001100100011001001011000100111010101010100101111011010111111010110111111010000100000011010000011110000011100011010000001101111010101010001110111010101011100100110111011000000110011100110101110011000011110100111110110111101010101010110011100011011011011100010110101110000100100000111010001101011000001001111000111111100000000110111100100001010101100111000101101010100001000001000100000010101111010101101111100100010000100011100111110001101000101010110011001111100100000000000001000101011110101011000010101011111000001101011110011011101010110000110000011001110101110011010000001100111100011011;
    reg[626:0] __serial__;

    wire[7:0] __tmsPattern__ = 8'b 01100110;
    wire[3:0] __preload_chain__ = 4'b0011;

    wire __tdo_pad_out__ = tdo_paden_o ? 1'bz : tdo;

    initial begin
        `ifdef VCD
            $dumpfile("dut.vcd");
            $dumpvars(0, testbench);
        `endif
        \clock = 0 ;
        \resetn = 0 ;
        \pkt_valid = 0 ;
        \read_enb_0 = 0 ;
        \read_enb_1 = 0 ;
        \read_enb_2 = 0 ;
        \data_in = 0 ;
        \tms = 0 ;
        \tck = 0 ;
        \tdi = 0 ;
        \trst = 0 ;

        tms = 1;
        #(`CLOCK_PERIOD) ;
        resetn = ~resetn;
        trst = 1;        
        #(`CLOCK_PERIOD) ;

        /*
            Test PreloadChain Instruction
        */
        shiftIR(__preload_chain__);
        enterShiftDR();

        for (i = 0; i < 627; i = i + 1) begin
            tdi = __serializable__[i];
            #(`CLOCK_PERIOD) ;
        end
        for(i = 0; i< 627; i = i + 1) begin
            __serial__[i] = __tdo_pad_out__;
            #(`CLOCK_PERIOD) ;
        end 

        if(__serial__ !== __serializable__) begin
            $error("EXECUTING_PRELOAD_CHAIN_INST_FAILED");
            $finish;
        end
        exitDR();

        $display("SUCCESS_STRING");
        $finish;
    end

    task shiftIR;
        input[3:0] __instruction__;
        integer i;
        begin
            for (i = 0; i< 5; i = i + 1) begin
                tms = __tmsPattern__[i];
                #(`CLOCK_PERIOD) ;
            end

            // At shift-IR: shift new instruction on tdi line
            for (i = 0; i < 4; i = i + 1) begin
                tdi = __instruction__[i];
                if(i == 3) begin
                    tms = __tmsPattern__[5];     // exit-ir
                end
                #(`CLOCK_PERIOD) ;
            end

            tms = __tmsPattern__[6];     // update-ir 
            #(`CLOCK_PERIOD) ;
            tms = __tmsPattern__[7];     // run test-idle
            #(`CLOCK_PERIOD * 3) ;
        end
    endtask

    task enterShiftDR;
        begin
            tms = 1;     // select DR
            #(`CLOCK_PERIOD) ;
            tms = 0;     // capture DR -- shift DR
            #(`CLOCK_PERIOD * 2) ;
        end
    endtask

    task exitDR;
        begin
            tms = 1;     // Exit DR -- update DR
            #(`CLOCK_PERIOD * 2) ;
            tms = 0;     // Run test-idle
            #(`CLOCK_PERIOD) ;
        end
    endtask
endmodule
