puts "Starting GDS generation..."
###############################################################################
# GDS Generation Script (Magic)
#
# Purpose:
#   Import the routed DEF from OpenROAD, merge standard-cell GDS,
#   and export the final GDSII layout.
#
# Run from:
#   RTL-to-GDSII/GDS
#
# Command:
# magic -dnull -noconsole -T ../../Tech_Lib/sky130A.tech < GDS_Export.tcl 2>&1 | tee Log/gds.log
###############################################################################
set GDS_DIR "../RESULTS/GDS"
file mkdir $GDS_DIR
#--------------------------------------------------------------------------
# Load Technology LEF
# Defines routing layers, vias, sites, and manufacturing rules.
#--------------------------------------------------------------------------
lef read ../../Tech_Lib/sky130_fd_sc_hd.tlef

#--------------------------------------------------------------------------
# Load Standard Cell LEF
# Provides abstract physical views of standard cells.
#--------------------------------------------------------------------------
lef read ../../Tech_Lib/sky130_fd_sc_hd_merged.lef

#--------------------------------------------------------------------------
# Load IO LEF
# Provides abstract views for IO filler cells.
#--------------------------------------------------------------------------
lef read ../../Tech_Lib/sky130io_fill.lef

#--------------------------------------------------------------------------
# Import routed DEF generated by OpenROAD.
#--------------------------------------------------------------------------
def read ../../PD/RESULTS/ROUTING/Routing.def

#--------------------------------------------------------------------------
# Load standard-cell GDS library.
# This replaces LEF abstracts with actual layout geometry.
#--------------------------------------------------------------------------
gds read ../../Tech_Lib/sky130_fd_sc_hd.gds

#--------------------------------------------------------------------------
# Load the top-level design.
#--------------------------------------------------------------------------
load router_top

#--------------------------------------------------------------------------
# Expand hierarchy before GDS export.
#--------------------------------------------------------------------------
select top cell
expand

#--------------------------------------------------------------------------
# Configure GDS export options.
#--------------------------------------------------------------------------
gds readonly true
gds rescale false

#--------------------------------------------------------------------------
# Export final GDSII.
#--------------------------------------------------------------------------
gds write $GDS_DIR/router_top.gds

puts ""
puts "========================================="
puts " GDS Generation Completed Successfully"
puts " Output : router_top.gds"
puts "========================================="

quit -noprompt