/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-06-23 22:27:10
*/
`include "/home/keyur/my_full_pdk/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v"
`include "SCAN/router_top_scan_netlist.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    reg[0:0] \clock ;
    reg[0:0] \read_enb_2 ;
    wire[0:0] \vld_out_2 ;
    wire[7:0] \data_out_0 ;
    wire[7:0] \data_out_1 ;
    wire[0:0] \busy ;
    reg[0:0] \read_enb_0 ;
    reg[0:0] \tck ;
    wire[0:0] \sout ;
    reg[0:0] \pkt_valid ;
    reg[0:0] \test ;
    wire[7:0] \data_out_2 ;
    reg[0:0] \sin ;
    reg[0:0] \read_enb_1 ;
    wire[0:0] \err ;
    reg[0:0] \resetn ;
    reg[0:0] \shift ;
    reg[7:0] \data_in ;
    wire[0:0] \vld_out_1 ;
    wire[0:0] \vld_out_0 ;

        always #(`CLOCK_PERIOD / 2) clock = ~clock; 
        always #(`CLOCK_PERIOD / 2) tck = ~tck; 

    router_top uut(
        .\clock ( \clock ) , .\read_enb_2 ( \read_enb_2 ) , .\vld_out_2 ( \vld_out_2 ) , .\data_out_0 ( \data_out_0 ) , .\data_out_1 ( \data_out_1 ) , .\busy ( \busy ) , .\read_enb_0 ( \read_enb_0 ) , .\tck ( \tck ) , .\sout ( \sout ) , .\pkt_valid ( \pkt_valid ) , .\test ( \test ) , .\data_out_2 ( \data_out_2 ) , .\sin ( \sin ) , .\read_enb_1 ( \read_enb_1 ) , .\err ( \err ) , .\resetn ( \resetn ) , .\shift ( \shift ) , .\data_in ( \data_in ) , .\vld_out_1 ( \vld_out_1 ) , .\vld_out_0 ( \vld_out_0 ) 
    ); 

    wire[626:0] __serializable__ =
        627'b001100000111110101000111001110010000011000101101100111000011101001010110010101100001111001000001100010111101001111100111100100101100001110100000001000110001011110001111000111011110110010000000111100101100000001101001110100101101100000000101101011000000111001001111010100011100100010001111011001111101111011101001110000110100011110100101000000111001011110100011100110001100000000000110110100010011111101001010101011111110001010001001100100111101110000101001111010010001010010110101001101000010010101001001100100001101001000100101011110111011011101110010100101100101011111100110000111000010101000110101010101000011011001011010111;
    reg[626:0] __serial__;
    integer i;
    initial begin
        `ifdef VCD
            $dumpfile("chain.vcd");
            $dumpvars(0, testbench);
        `endif
        \clock = 0 ;
        \resetn = 0 ;
        \pkt_valid = 0 ;
        \read_enb_0 = 0 ;
        \read_enb_1 = 0 ;
        \read_enb_2 = 0 ;
        \data_in = 0 ;
        \sin = 0 ;
        \shift = 0 ;
        \tck = 0 ;
        \test = 0 ;

        #(`CLOCK_PERIOD*5);
        resetn = ~resetn;
        shift = 1;
        test = 1;
        for (i = 0; i < 627; i = i + 1) begin
            sin = __serializable__[i];
            #(`CLOCK_PERIOD);
        end
        for (i = 0; i < 627; i = i + 1) begin
            __serial__[i] = sout;
            #(`CLOCK_PERIOD);
        end
        if (__serializable__ === __serial__) begin
            $display("Success: expected %b got %b", __serializable__, __serial__);
            $display("SUCCESS_STRING");
        end else begin
            $display("Failed: expected %b got %b", __serializable__, __serial__);
        end
        $finish;
    end
endmodule
