/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-07-01 09:37:38
*/
`include "../Tech_Lib/sky130_fd_sc_hd.v"
`include "SCAN/router_top_scan_netlist.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    wire[0:0] \busy ;
    reg[0:0] \shift ;
    wire[0:0] \vld_out_1 ;
    reg[0:0] \read_enb_2 ;
    reg[0:0] \pkt_valid ;
    reg[0:0] \tck ;
    reg[0:0] \test ;
    reg[0:0] \sin ;
    wire[0:0] \err ;
    reg[7:0] \data_in ;
    wire[0:0] \sout ;
    reg[0:0] \resetn ;
    reg[0:0] \clock ;
    reg[0:0] \read_enb_1 ;
    wire[0:0] \vld_out_2 ;
    reg[0:0] \read_enb_0 ;
    wire[7:0] \data_out_1 ;
    wire[7:0] \data_out_0 ;
    wire[7:0] \data_out_2 ;
    wire[0:0] \vld_out_0 ;

        always #(`CLOCK_PERIOD / 2) clock = ~clock; 
        always #(`CLOCK_PERIOD / 2) tck = ~tck; 

    router_top uut(
        .\busy ( \busy ) , .\shift ( \shift ) , .\vld_out_1 ( \vld_out_1 ) , .\read_enb_2 ( \read_enb_2 ) , .\pkt_valid ( \pkt_valid ) , .\tck ( \tck ) , .\test ( \test ) , .\sin ( \sin ) , .\err ( \err ) , .\data_in ( \data_in ) , .\sout ( \sout ) , .\resetn ( \resetn ) , .\clock ( \clock ) , .\read_enb_1 ( \read_enb_1 ) , .\vld_out_2 ( \vld_out_2 ) , .\read_enb_0 ( \read_enb_0 ) , .\data_out_1 ( \data_out_1 ) , .\data_out_0 ( \data_out_0 ) , .\data_out_2 ( \data_out_2 ) , .\vld_out_0 ( \vld_out_0 ) 
    ); 

    wire[626:0] __serializable__ =
        627'b010110111111101110100110001111111001000001010001001110010110111011111111011011011000001101001100001100001111000010000000100010101011100110110110101110101110010001110010000011000101010101111111001010110000000111110010000100001000001011101011000110101000100001100111101111010000001001100000100100000111101101000000101111000111001101101110010111111100001000001001111110111001001110110000001001000010101101001100000101000100111101010001011111010111011001100011101101010011110101010001101001110000110100111110110011111011101010101100101111010110101010011100100111011100111010001101001001000101000001000010000011001110111110010010111;
    reg[626:0] __serial__;
    integer i;
    initial begin
        `ifdef VCD
            $dumpfile("chain.vcd");
            $dumpvars(0, testbench);
        `endif
        \clock = 0 ;
        \resetn = 0 ;
        \pkt_valid = 0 ;
        \read_enb_0 = 0 ;
        \read_enb_1 = 0 ;
        \read_enb_2 = 0 ;
        \data_in = 0 ;
        \sin = 0 ;
        \shift = 0 ;
        \tck = 0 ;
        \test = 0 ;

        #(`CLOCK_PERIOD*5);
        resetn = ~resetn;
        shift = 1;
        test = 1;
        for (i = 0; i < 627; i = i + 1) begin
            sin = __serializable__[i];
            #(`CLOCK_PERIOD);
        end
        for (i = 0; i < 627; i = i + 1) begin
            __serial__[i] = sout;
            #(`CLOCK_PERIOD);
        end
        if (__serializable__ === __serial__) begin
            $display("Success: expected %b got %b", __serializable__, __serial__);
            $display("SUCCESS_STRING");
        end else begin
            $display("Failed: expected %b got %b", __serializable__, __serial__);
        end
        $finish;
    end
endmodule
